FROM node:18-alpine AS builder

WORKDIR /app
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install
COPY . .

RUN apk update \
    && apk upgrade \
    && apk add \
        alpine-sdk \
        bash \
        python3

RUN apk update && apk add --no-cache nmap && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache \
      chromium \
      harfbuzz \
      "freetype>2.8" \
      ttf-freefont \
      nss

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

ENV YARN_CACHE_FOLDER=/tmp/yarn_cache
RUN apk --no-cache add build-base python3

CMD ["yarn", "start:dev"]